# 公共配置文件

spring:
  application:
    name: @project.name@
  profiles:
    # 该配置决定使用 application-dev.yml 还是 application-prod.yml 作为附加配置文件
    active: @profile@

mqttx:
  version: @version@
  # broker-id 用于区分集群内部机器，不同的 broker 必须分配不同的 id
  broker-id: @broker.id@
  # kryo 比 json 更具优势
  serialize-strategy: kryo
  auth:
    url: "http://localhost:8080/auth"
