# 测试环境配置文件

spring:
  application:
    name: mqttx

mqttx:
  enable-test-mode: true
  web-socket:
    enable: true
  sys-topic:
    enable: true

# 1 开启 ssl 配置示例
#spring:
#  redis:
#    host: localhost
#
#mqttx:
#  ssl:
#    key-store-password: 123456
#    key-store-location: classpath:tls/mqttx.keystore
#    enable: true
#    client-auth: NONE
#    key-store-type: pkcs12

# 2 桥接消息配置示例
#spring:
#  kafka:
#    bootstrap-servers:
#      - localhost:9092
#    producer:
#      acks: 1
#      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#
#mqttx:
#  message-bridge:
#    bridge-topics:
#      - "/bridge/topic"
#      - "mqttx/love"
#    enable: true