# 测试环境配置文件

mqttx:
  enable-test-mode: true
  web-socket:
    enable: true

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger){cyan} %clr([%4.4L]){cyan} %clr(:){faint} %m%n"

# 1 开启 ssl 配置示例
#spring:
#  redis:
#    host: localhost
#
#mqttx:
#  ssl:
#    key-store-password: 123456
#    key-store-location: classpath:tls/mqttx.keystore
#    enable: true
#    client-auth: NONE
#    key-store-type: pkcs12

# 2 桥接消息配置示例
#spring:
#  kafka:
#    bootstrap-servers:
#      - localhost:9092
#    producer:
#      acks: 1
#      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#
#mqttx:
#  message-bridge:
#    bridge-topics:
#      - "/bridge/topic"
#      - "mqttx/love"
#    enable: true