# 公共配置文件

spring:
  application:
    name: @project.name@
  profiles:
    # 该配置决定使用 application-dev.yml 还是 application-prod.yml 作为附加配置文件
    active: @profile@

mqttx:
  broker-id: "001"
  version: @version@
  # kryo 比 json 更具优势
  serialize-strategy: kryo
