# 公共配置文件

spring:
  application:
    name: @broker.name@
  profiles:
    # 该配置决定使用 application-dev.yml 还是 application-prod.yml 作为附加配置文件
    active: @profile@

mqttx:
  version: @version@
  broker-id: @broker.id@

